import type { APIRoute } from 'astro';

/**
 * Dynamic robots.txt.
 *
 * For preview / staging domains (workers.dev, pages.dev, netlify.app, vercel.app)
 * we return a "Disallow: /" body so search engines don't index two copies of the
 * site. The canonical production hostname returns the full crawl rules.
 *
 * Reference: https://www.robotstxt.org/
 */

const PREVIEW_HOST_SUFFIXES = ['.workers.dev', '.pages.dev', '.netlify.app', '.vercel.app'];

const CANONICAL_BODY = `# Alexey Kachan Agency — robots.txt

User-agent: *
Allow: /
Disallow: /api/
Disallow: /admin/
Disallow: /draft/
Disallow: /thank-you/
Disallow: /danke/
Disallow: /merci/
Disallow: /gracias/
Disallow: /grazie/
Disallow: /multumim/
Disallow: /dyakuemo/
Disallow: /spasibo/
Disallow: /*?utm_*
Disallow: /*?gclid=*
Disallow: /*?fbclid=*
Disallow: /*?ref=*

# AI training crawlers — blocked by default.
# Flip to Allow per-bot if/when business decides to allow training-data ingestion.
User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: OAI-SearchBot
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-Web
Disallow: /

User-agent: ClaudeBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: PerplexityBot
Disallow: /

User-agent: Bytespider
Disallow: /

User-agent: Amazonbot
Disallow: /

User-agent: cohere-ai
Disallow: /

# Sitemap (auto-generated by @astrojs/sitemap with hreflang for 8 languages)
Sitemap: https://alexeykachan.com/sitemap-index.xml
Host: https://alexeykachan.com
`;

const PREVIEW_BODY = `# Preview / staging deployment — fully blocked from indexing.
# The canonical site lives at https://alexeykachan.com.

User-agent: *
Disallow: /
`;

export const GET: APIRoute = ({ url }) => {
  const isPreview = PREVIEW_HOST_SUFFIXES.some((suffix) => url.host.endsWith(suffix));
  const body = isPreview ? PREVIEW_BODY : CANONICAL_BODY;
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Short cache so preview <-> production switching is fast
      'Cache-Control': 'public, max-age=300, s-maxage=300',
    },
  });
};
